- name: Create configured users
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    append: true
    password_lock: true
    state: present
  loop: "{{ bootstrap_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add SSH public keys for configured users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
  loop: "{{ bootstrap_users }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.ssh_public_key is defined